info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    user:
      path: /user/**
      serviceId: user-service
      stripPrefix: false
    product:
      path: /product/**
      serviceId: product-category-service
      stripPrefix: false
    category:
          path: /category/**
          serviceId: product-category-service
          stripPrefix: false

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO