#%RAML 0.8
title: Category Service
baseUri: http://localhost
mediaType: application/json
version: v0.1

/category:
  post:
    description: creates a new category
    body:
      application/json:
        schema: |
          { 
            "$schema": "http://json-schema.org/draft-04/schema#",
            "id": "http://jsonschema.net",
            "type": "object",
            "required": "true",
            "properties":
              {
                "name": "string"
              }
          }
  get:
    description: get all categories
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "type": "object",
                  "required": "true",
                  "properties":
                  {
                    "categories": ["object"]
                  }
              }
  /{id}:
    delete:
      description: delete a specific category
    get:
      description: get a specific category by id
      responses:
        200:
          body:
            application/json:
              schema: |
                { 
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "type": "object",
                  "required": "true",
                  "properties":
                    {
                      "id": "integer",
                      "name": "string"
                    }
                }
